they talk about us
Meule-Corporation/raclette pull request #64
Opened 2021-12-06 18:06 UTC by LaSylv

2021-12-06 18:10 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +import CardCheese from '../components/CardCheese';
Absolute

2021-12-06 18:13 UTC, hy0ug0 requested changes

2021-12-06 18:13 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +              <v-img style="background-color: white" class="align-end"  src="/img/articles/konbini.png">
faut pas mettre les paths en relatif là pour le coup ?

2021-12-07 16:31 UTC, hy0ug0 requested changes

2021-12-07 16:31 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +        <a target="_blank" :href="article.link">
Ajoute le rel noopenner je sais pas quoi je sais pas à quoi ça sert mais ça fait pro

2021-12-07 16:31 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +        <a target="_blank" :href="article.link">
+ on peut pas faire mieux que de wrapper la carte dans une balise `<a>` ?

2021-12-07 16:31 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +                  :src="'/img/articles/' + article.img"
```suggestion
                  :src="`/img/articles/${article.img}`"
```

2021-12-07 16:31 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +                  alt="user"
Pas ouf pour le SEO ça je pense ?

2021-12-07 16:31 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +            <v-card-text class="font-italic">
Je crois que tu as une class pour les quotes dans Vuetify ça rend pas mieux ?

2021-12-07 16:31 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +  name: 'AboutUs',
Nope

2021-12-07 17:09 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +        <a target="_blank" :href="article.link">
pour le seo il vaut mieux pas mettre le rel de ce que je vois, on veut pas cacher que les users vienennt de chez nous

2021-12-07 17:10 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +        <a target="_blank" :href="article.link">
je pense qu'il faut pas mettre rel noopener pour le SEO

Pareil, je laisserai bien le <a> pour le seo au lieu d'un @click

2021-12-07 17:10 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +                  :src="'/img/articles/' + article.img"
yes

2021-12-07 17:11 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +                  alt="user"
yes je met le nom du site

2021-12-07 17:13 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +                  :src="'/img/articles/' + article.img"
j'ai mis des blockquote, ke sais pas si c'est mieux, c'est plus en italique en tout vas

2021-12-07 17:14 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +  name: 'AboutUs',
nope

2021-12-07 17:34 UTC, hy0ug0 approved these changes

2021-12-07 17:34 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +        <a target="_blank" :href="article.link">
Mouais OK c'est toi l'expert SEO par contre c'est moche dans le code lol

2021-12-07 17:35 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +                  :src="'/img/articles/' + article.img"
Test quand même au cas où Webpack arriverait pas à résoudre les paths

2021-12-07 17:54 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +            <v-card-text class="font-italic">
j'ai mis un <blockquote>

2021-12-07 17:54 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +                  :src="'/img/articles/' + article.img"
tkt j'ai testé

2021-12-07 17:55 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +        <a target="_blank" :href="article.link">
je trouve ca va, semantiquement ca a du sens non ?

2021-12-08 08:46 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +  <v-row justify="center" align="center" class="mr-5">
En vrai c'est pas normal d'avoir à faire `class="mr-5"` à ce niveau là, il manque pas un `v-col` ou un truc du genre ?

2021-12-08 08:46 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +    <h2 class="text-sm-h2 my-6 text-center">Ils parlent de nous</h2>
Il faut une clé ici pas de texte en dure

2021-12-08 08:46 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +        <a v-if="item.mode === 'article' || item.mode === 'audio'" target="_blank" :href="item.link">
Fais une computed si tu repush un truc

2021-12-08 08:47 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +                <source :src="'/'+ item.interview +'.mp3'" type="audio/mp3">
Tu aimes bien faire tes concaténation comme en Java 🤓

2021-12-08 08:49 UTC, hy0ug0 commented on pages/they-talk-about-us.vue
> +        <a target="_blank" :href="article.link">
Pas sûr mais OSEF

2021-12-08 11:20 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +    <h2 class="text-sm-h2 my-6 text-center">Ils parlent de nous</h2>
yes

2021-12-08 11:20 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +        <a v-if="item.mode === 'article' || item.mode === 'audio'" target="_blank" :href="item.link">
j'ai fait une methode car ca utilise un truc du vfor

2021-12-08 11:21 UTC, LaSylv commented on pages/they-talk-about-us.vue
> +                <source :src="'/'+ item.interview +'.mp3'" type="audio/mp3">
soon en java les tempalte string

2021-12-08 13:17 UTC, merged