feat(seo): jsonld first impl
Meule-Corporation/raclette pull request #9
Opened 2021-10-02 10:02 UTC by Glosur

2021-10-02 11:44 UTC, hy0ug0 requested changes

2021-10-02 11:44 UTC, hy0ug0 commented on pages/index.vue
> +          "text": "<p></p><p>Online purchases may be returned via a major parcel carrier. <a href=http://example.com/returns> Click here </a> to initiate a return.</p>"
WTF ?

2021-10-02 15:19 UTC, Glosur commented on pages/index.vue
> +          "text": "<p></p><p>Online purchases may be returned via a major parcel carrier. <a href=http://example.com/returns> Click here </a> to initiate a return.</p>"
c'est des tests fallait pas review tu suis pas le jira ?

2021-10-02 15:31 UTC, hy0ug0 commented on pages/index.vue
> +          "text": "<p></p><p>Online purchases may be returned via a major parcel carrier. <a href=http://example.com/returns> Click here </a> to initiate a return.</p>"
Faut merger ou pas ? Tu mets ta PR en draft sinon ! 
La prochaine fois tu es bann fait attention

2021-10-03 09:21 UTC, Glosur commented on pages/index.vue
> +          "text": "<p></p><p>Online purchases may be returned via a major parcel carrier. <a href=http://example.com/returns> Click here </a> to initiate a return.</p>"
comment on fait ?

2021-10-03 17:10 UTC, hy0ug0 commented on pages/index.vue
> +          "text": "<p></p><p>Online purchases may be returned via a major parcel carrier. <a href=http://example.com/returns> Click here </a> to initiate a return.</p>"
Bonne question

2021-11-12 08:12 UTC, closed without merging